app:
  oauth2:
    redirectUri: http://localhost:8080/api/v1/o/login-rediret

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lattmat
    username: root
    password: Zayar2142000
  jpa:
    hibernate:
      ddl-auto: create-drop