server:
  servlet:
    context-path: /api/v1
  tomcat:
    use-relative-redirects: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
  forward-headers-strategy: framework

spring:
  config:
    import: optional:configserver:http://localhost:9001
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 558074316688-866sca12dqj9bdq8mq817dqh3gmlgkon.apps.googleusercontent.com
            clientSecret: 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
#            clientId: 558074316688-tg9bhdnush0fnhesc623b6uov8hu0d5t.apps.googleusercontent.com
#            clientSecret: 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
          facebook:
            clientId: 859141935812181
            clientSecret: a5ccfb6a98e11b9336673ec427c56df7
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v12.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v12.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v12.0/me?fields=id,email,name,picture.type(large)
            userNameAttribute: id
  profiles:
    active: uat
  application:
    name: lattmat

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"