server:
  servlet:
    context-path: /api/v1
  tomcat:
    use-relative-redirects: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
  forward-headers-strategy: framework

spring:
  config:
    import: optional:configserver:http://localhost:9001
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 558074316688-866sca12dqj9bdq8mq817dqh3gmlgkon.apps.googleusercontent.com
            clientSecret: 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
          facebook:
            clientId: 3485687095080374
            clientSecret: 3bb418d7cc81ecc9125d122a79f5f68e
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v17.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v17.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v17.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,picture.width(250).height(250)
  profiles:
    active: uat
  application:
    name: lattmat

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  ratelimiter:
    instances:
      login_limiter:
        limitForPeriod: 3
        limitRefreshPeriod: 15s
        timeoutDuration: 15s


#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"