app:
  oauth2:
    redirectUri: http://localhost:8080/api/v1/o/login-rediret

server:
  servlet:
    context-path: /api/v1

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 558074316688-866sca12dqj9bdq8mq817dqh3gmlgkon.apps.googleusercontent.com
            clientSecret: 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
          facebook:
            clientId: 291236720533751
            clientSecret: 562bb8b7ba7b026828dd76d935bce354
            scope:
              - email
              - public_profile
  profiles:
    active: dev
  application:
    name: LATTMAT

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html