server:
  servlet:
    context-path: /api/v1

spring:
  config:
    import: optional:configserver:http://localhost:9001
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 558074316688-866sca12dqj9bdq8mq817dqh3gmlgkon.apps.googleusercontent.com
            clientSecret: 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
          facebook:
            clientId: 859141935812181
            clientSecret: a5ccfb6a98e11b9336673ec427c56df7
            scope:
              - email
              - public_profile
  profiles:
    active: uat
  application:
    name: lattmat

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"