app:
  oauth2:
    redirectUri: http://localhost:8888/home

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lattmat
    username: root
    password: Zayar2142000
  jpa:
    hibernate:
      ddl-auto: update