app:
  oauth2:
    redirectUri: http://localhost:8080/api/v1/o/login-rediret

server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://dpg-cksupf8168ec73emr0rg-a.singapore-postgres.render.com/lattmat_db
    username: laddmat_db_admin
    password: 45EJZtgO0xkgb7yAbHZ0aZVrdqBDS9kL
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 558074316688-866sca12dqj9bdq8mq817dqh3gmlgkon.apps.googleusercontent.com
            clientSecret: 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
          facebook:
            clientId: 1359854274885580
            clientSecret: ea60322cf64dda9e7ce6c2f8715a4c4a
            scope:
              - email
              - public_profile